/*
VOTOS VALORES:

NULOS = 0
BRANCOS = 1000
 */
package client;

import java.awt.Color;
import java.sql.SQLException;


public class Urna extends javax.swing.JFrame {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    //guardara o voto final do eleitor
    
    String stringVoto;
    private Controller ctr;


    public Urna(Controller ctr) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Urna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Urna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Urna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Urna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //padrão do Jframe java
        initComponents();

        //inicializa variaveis
        stringVoto = "";
        this.ctr = ctr;

        //pintar os botões com as respectivas cores
        jButtonVotar.setBackground(Color.GREEN);
        jButtonAnular.setBackground(Color.RED);
        jButton0.setBackground(Color.GRAY);
        jButton1.setBackground(Color.GRAY);
        jButton2.setBackground(Color.GRAY);
        jButton3.setBackground(Color.GRAY);
        jButton4.setBackground(Color.GRAY);
        jButton5.setBackground(Color.GRAY);
        jButton6.setBackground(Color.GRAY);
        jButton7.setBackground(Color.GRAY);
        jButton8.setBackground(Color.GRAY);
        jButton9.setBackground(Color.GRAY);

        jPanel1.setBackground(Color.DARK_GRAY);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButtonBranco = new javax.swing.JButton();
        jButtonVotar = new javax.swing.JButton();
        jButtonAnular = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldVoto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonApaga = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("2");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("3");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("1");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setText("4");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setText("5");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton6.setText("6");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton7.setText("7");
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton8.setText("8");
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton9.setText("9");
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton0.setText("0");
        jButton0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        jButtonBranco.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonBranco.setText("BRANCO");
        jButtonBranco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButtonBranco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrancoActionPerformed(evt);
            }
        });

        jButtonVotar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonVotar.setText("VOTAR");
        jButtonVotar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButtonVotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonVotarActionPerformed(evt);
                } catch (SQLException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        });

        jButtonAnular.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonAnular.setText("NULO");
        jButtonAnular.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButtonAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnularActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("O VOTO VAI PARA:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("999 para listar os candidatos");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("888 para finalizar a votação");

        jTextFieldVoto.setEditable(false);
        jTextFieldVoto.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jTextFieldVoto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldVoto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jTextFieldVoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVotoActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("´");
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                .addGap(2, 2, 2)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                                        .addComponent(jTextFieldVoto))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldVoto, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        jButtonApaga.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonApaga.setText("Apagar");
        jButtonApaga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButtonApaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jButtonVotar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jButtonAnular, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jButtonBranco, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(29, 29, 29)
                                                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButtonApaga, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(60, 60, 60)))
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonApaga, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jButtonVotar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonAnular, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButtonBranco, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        //compara o texto digitado com a string voto , e caso seja igual, preenchera com o 2
        //caso contrário, irá concatenar com o valor da string atual em jtextfieldvoto + 2
        if (jTextFieldVoto.getText().equalsIgnoreCase("voto invalido") || jTextFieldVoto.getText().equalsIgnoreCase("Voto Em Branco") || jTextFieldVoto.getText().equalsIgnoreCase("Voto Nulo")) {
            jTextFieldVoto.setText("2");

        } else {
            jTextFieldVoto.setText(jTextFieldVoto.getText() + "2");
        }
        //converter em inteiro para poder comparar o valor digitado e comparar com
        //um valor limite para poder limitar o numero de votos digitados na tela.
        //no caso o valor máximo aceito é 999 e o minimo é 1
        int comp = Integer.parseInt(jTextFieldVoto.getText());
        if (comp > 999 || comp < 1) {
            jTextFieldVoto.setText("voto invalido");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        //compara o texto digitado com a string voto , e caso seja igual, preenchera com o 8
        //caso contrário, irá concatenar com o valor da string atual em jtextfieldvoto + 8
        if (jTextFieldVoto.getText().equalsIgnoreCase("voto invalido") || jTextFieldVoto.getText().equalsIgnoreCase("Voto Em Branco") || jTextFieldVoto.getText().equalsIgnoreCase("Voto Nulo")) {
            jTextFieldVoto.setText("8");

        } else {
            jTextFieldVoto.setText(jTextFieldVoto.getText() + "8");
        }


        //converter em inteiro para poder comparar o valor digitado e comparar com
        //um valor limite para poder limitar o numero de votos digitados na tela.
        //no caso o valor máximo aceito é 999 e o minimo é 1
        int comp = Integer.parseInt(jTextFieldVoto.getText());

        if (comp > 999 || comp < 1) {
            jTextFieldVoto.setText("voto invalido");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //valor máximo permitido na tela para votar.
        String str = "1000";
        if (jTextFieldVoto.getText().equalsIgnoreCase("voto invalido") || jTextFieldVoto.getText().equalsIgnoreCase("Voto Em Branco") || jTextFieldVoto.getText().equalsIgnoreCase("Voto Nulo")) {
            jTextFieldVoto.setText("1");

        } else {
            jTextFieldVoto.setText(jTextFieldVoto.getText() + "1");
        }

        //converter em inteiro para poder comparar o valor digitado e comparar com
        //um valor limite para poder limitar o numero de votos digitados na tela.
        //no caso o valor máximo aceito é 999 e o minimo é 1
        int comp = Integer.parseInt(jTextFieldVoto.getText());
        if (comp > 999 || comp < 1) {
            jTextFieldVoto.setText("voto invalido");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (jTextFieldVoto.getText().equalsIgnoreCase("voto invalido") || jTextFieldVoto.getText().equalsIgnoreCase("Voto Em Branco") || jTextFieldVoto.getText().equalsIgnoreCase("Voto Nulo")) {
            jTextFieldVoto.setText("3");

        } else {
            jTextFieldVoto.setText(jTextFieldVoto.getText() + "3");
        }

        //converter em inteiro para poder comparar o valor digitado e comparar com
        //um valor limite para poder limitar o numero de votos digitados na tela.
        //no caso o valor máximo aceito é 999 e o minimo é 1
        int comp = Integer.parseInt(jTextFieldVoto.getText());
        if (comp > 999 || comp < 1) {
            jTextFieldVoto.setText("voto invalido");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        if (jTextFieldVoto.getText().equalsIgnoreCase("voto invalido") || jTextFieldVoto.getText().equalsIgnoreCase("Voto Em Branco") || jTextFieldVoto.getText().equalsIgnoreCase("Voto Nulo")) {
            jTextFieldVoto.setText("4");

        } else {
            jTextFieldVoto.setText(jTextFieldVoto.getText() + "4");
        }
        //converter em inteiro para poder comparar o valor digitado e comparar com
        //um valor limite para poder limitar o numero de votos digitados na tela.
        //no caso o valor máximo aceito é 999 e o minimo é 1
        int comp = Integer.parseInt(jTextFieldVoto.getText());
        if (comp > 999 || comp < 1) {
            jTextFieldVoto.setText("voto invalido");
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        if (jTextFieldVoto.getText().equalsIgnoreCase("voto invalido") || jTextFieldVoto.getText().equalsIgnoreCase("Voto Em Branco") || jTextFieldVoto.getText().equalsIgnoreCase("Voto Nulo")) {
            jTextFieldVoto.setText("5");

        } else {
            jTextFieldVoto.setText(jTextFieldVoto.getText() + "5");
        }

        //converter em inteiro para poder comparar o valor digitado e comparar com
        //um valor limite para poder limitar o numero de votos digitados na tela.
        //no caso o valor máximo aceito é 999 e o minimo é 1
        int comp = Integer.parseInt(jTextFieldVoto.getText());
        if (comp > 999 || comp < 1) {
            jTextFieldVoto.setText("voto invalido");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        if (jTextFieldVoto.getText().equalsIgnoreCase("voto invalido") || jTextFieldVoto.getText().equalsIgnoreCase("Voto Em Branco") || jTextFieldVoto.getText().equalsIgnoreCase("Voto Nulo")) {
            jTextFieldVoto.setText("6");

        } else {
            jTextFieldVoto.setText(jTextFieldVoto.getText() + "6");
        }

        //converter em inteiro para poder comparar o valor digitado e comparar com
        //um valor limite para poder limitar o numero de votos digitados na tela.
        //no caso o valor máximo aceito é 999 e o minimo é 1
        int comp = Integer.parseInt(jTextFieldVoto.getText());
        if (comp > 999 || comp < 1) {
            jTextFieldVoto.setText("voto invalido");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        if (jTextFieldVoto.getText().equalsIgnoreCase("voto invalido") || jTextFieldVoto.getText().equalsIgnoreCase("Voto Em Branco") || jTextFieldVoto.getText().equalsIgnoreCase("Voto Nulo")) {
            jTextFieldVoto.setText("7");

        } else {
            jTextFieldVoto.setText(jTextFieldVoto.getText() + "7");
        }
        //converter em inteiro para poder comparar o valor digitado e comparar com
        //um valor limite para poder limitar o numero de votos digitados na tela.
        //no caso o valor máximo aceito é 999 e o minimo é 1
        int comp = Integer.parseInt(jTextFieldVoto.getText());
        if (comp > 999 || comp < 1) {
            jTextFieldVoto.setText("voto invalido");
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        if (jTextFieldVoto.getText().equalsIgnoreCase("voto invalido") || jTextFieldVoto.getText().equalsIgnoreCase("Voto Em Branco") || jTextFieldVoto.getText().equalsIgnoreCase("Voto Nulo")) {
            jTextFieldVoto.setText("9");

        } else {
            jTextFieldVoto.setText(jTextFieldVoto.getText() + "9");
        }

        //converter em inteiro para poder comparar o valor digitado e comparar com
        //um valor limite para poder limitar o numero de votos digitados na tela.
        //no caso o valor máximo aceito é 999 e o minimo é 1
        int comp = Integer.parseInt(jTextFieldVoto.getText());
        if (comp > 999 || comp < 1) {
            jTextFieldVoto.setText("voto invalido");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed

        if (jTextFieldVoto.getText().equalsIgnoreCase("voto invalido") || jTextFieldVoto.getText().equalsIgnoreCase("Voto Em Branco") || jTextFieldVoto.getText().equalsIgnoreCase("Voto Nulo")) {
            jTextFieldVoto.setText("0");

        } else {
            jTextFieldVoto.setText(jTextFieldVoto.getText() + "0");
        }
        //converter em inteiro para poder comparar o valor digitado e comparar com
        //um valor limite para poder limitar o numero de votos digitados na tela.
        //no caso o valor máximo aceito é 999 e o minimo é 1
        int comp = Integer.parseInt(jTextFieldVoto.getText());
        if (comp > 999 || comp < 1) {
            jTextFieldVoto.setText("voto invalido");
        }

    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButtonApagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagaActionPerformed

        jTextFieldVoto.setText("");


    }//GEN-LAST:event_jButtonApagaActionPerformed

    private void jButtonBrancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrancoActionPerformed

        //Se votado em branco, será exibido na tela, voto em branco
        jTextFieldVoto.setText("Voto em Branco");
    }//GEN-LAST:event_jButtonBrancoActionPerformed

    private void jButtonVotarActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_jButtonVotarActionPerformed

        if (!(jTextFieldVoto.getText().equalsIgnoreCase("voto invalido"))) {
            //guardar o voto na variavel stringVoto.
            if (jTextFieldVoto.getText().equalsIgnoreCase("Voto em Branco")) {
                stringVoto = "1000";

            } else if (jTextFieldVoto.getText().equalsIgnoreCase("Voto Nulo")) {
                stringVoto = "0";
            } else {
                stringVoto = jTextFieldVoto.getText();

            }

            jTextFieldVoto.setText("");


            ctr.processVote(stringVoto);


        } else {

            stringVoto = "";
        }

    }//GEN-LAST:event_jButtonVotarActionPerformed

    private void jButtonAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnularActionPerformed

        //Se votado nulo, será exibido na tela, voto nulo
        jTextFieldVoto.setText("Voto Nulo");
    }//GEN-LAST:event_jButtonAnularActionPerformed

    private void jTextFieldVotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVotoActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAnular;
    private javax.swing.JButton jButtonApaga;
    private javax.swing.JButton jButtonBranco;
    private javax.swing.JButton jButtonVotar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    public javax.swing.JTextField jTextFieldVoto;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the voto
     */
    public String getstringVoto() {
        return stringVoto;
    }

    /**
     * @param voto the voto to set
     */
    public void setstringVoto(String voto) {
        this.stringVoto = voto;
    }

    /**
     * @return the jTextFieldVoto
     */
    public javax.swing.JTextField getjTextFieldVoto() {
        return jTextFieldVoto;
    }

    /**
     * @param jTextFieldVoto the jTextFieldVoto to set
     */
    public void setjTextFieldVoto(javax.swing.JTextField jTextFieldVoto) {
        this.jTextFieldVoto = jTextFieldVoto;
    }

    /**
     * @return the jTextArea1
     */
    public javax.swing.JTextArea getjTextArea1() {
        return jTextArea1;
    }


}
